// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetMvcBeer.Data;

namespace ProjetMvcBeer.Migrations
{
    [DbContext(typeof(ProjetMvcBeerContext))]
    [Migration("20220113141120_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ProjetMvcBeer.Models.Beer", b =>
                {
                    b.Property<int>("BeerID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("AlcoolDegree")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.HasKey("BeerID");

                    b.ToTable("Beer");
                });

            modelBuilder.Entity("ProjetMvcBeer.Models.Devis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devis");
                });

            modelBuilder.Entity("ProjetMvcBeer.Models.LigneDeVieDevis", b =>
                {
                    b.Property<int>("LigneDeVieDevisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevisID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LigneDeVieDevisID");

                    b.HasIndex("BeerID");

                    b.HasIndex("DevisID");

                    b.ToTable("LigneDeVieDevis");
                });

            modelBuilder.Entity("ProjetMvcBeer.Models.MonCompte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MonCompte");
                });

            modelBuilder.Entity("ProjetMvcBeer.Models.LigneDeVieDevis", b =>
                {
                    b.HasOne("ProjetMvcBeer.Models.Beer", "Beer")
                        .WithMany("ListLigneDeVieDevis")
                        .HasForeignKey("BeerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetMvcBeer.Models.Devis", "Devis")
                        .WithMany("ListeLigneDeVieDevis")
                        .HasForeignKey("DevisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Devis");
                });

            modelBuilder.Entity("ProjetMvcBeer.Models.Beer", b =>
                {
                    b.Navigation("ListLigneDeVieDevis");
                });

            modelBuilder.Entity("ProjetMvcBeer.Models.Devis", b =>
                {
                    b.Navigation("ListeLigneDeVieDevis");
                });
#pragma warning restore 612, 618
        }
    }
}
